### ISSUE TITLE
test

### ISSUE THREAD

**Issue by jimaek** [jimaek/bashlogo.com#5]
test

**Comment by jimaek** [comment]
@globalping ping google.com from Germany

**Comment by globalping** [comment]
Something is wrong :( Validation Failed

**Comment by jimaek** [comment]
@globalping help

**Comment by globalping** [comment]
The Globalping bot is a simple interface to interact with the Globalping API and run global networking tests. Need a traceroute done from Japan? Or check the ping latency of an endpoint from Brazil? Just ask me!

*Manual*
The Globalping Bot follows a similar format to the CLI but it's more human friendly. It currently supports only the traceroute and ping commands. 
```
@globalping {command} {endpoint} from {city or country or continent or region or US state or ASN or ISP name} limit {how many results you want to get}
e.g. 
ping google.com from New York
traceroute 1.2.3.4 from Europe limit 2
ping 1.2.3.4 from AS80085
```
